feat: Break out `custodial-ownership-token` directory in maple-core to be a submodule dapptools project (SC-3052))
maple-labs/custodial-ownership-token pull request #1
Opened 2021-07-30 15:17 UTC by satyamakgec

2021-08-02 01:46 UTC, lucas-manuel commented
Tests not compiling @satyamakgec

2021-08-02 14:53 UTC, deluca-mike requested changes
`modules/openzeppelin-contracts` is not the correct `v3.3.0` commit

2021-08-02 14:53 UTC, deluca-mike commented on Makefile
> +test    :; ./test.sh
new line needed at the end of the file

2021-08-02 14:53 UTC, deluca-mike commented on config/ci.json
> +    },
Can be removed at its not a unique entrypoint with respect to ci.

2021-08-02 14:53 UTC, deluca-mike commented on config/dev.json
> +    },
Can be removed at its not a unique entrypoint with respect to dev.

2021-08-02 14:53 UTC, deluca-mike commented on config/prod.json
> +    },
Can be removed at its not a unique entrypoint with respect to prod.

2021-08-02 14:53 UTC, deluca-mike commented on contracts/test/ERC2258.t.sol
> +import { IERC20 } from "../../modules/openzeppelin-contracts/contracts/token/ERC20/IERC20.sol";
```suggestion
import { DSTest } from "../../modules/ds-test/src/test.sol";
import { IERC20 } from "../../modules/openzeppelin-contracts/contracts/token/ERC20/IERC20.sol";

import { ERC2258 } from "../ERC2258.sol";

import { Custodian }      from "./accounts/Custodian.sol";
import { ERC2258Account } from "./accounts/ERC2258Account.sol";
```

2021-08-02 14:53 UTC, deluca-mike commented on contracts/test/ERC2258.t.sol
> +}
new line needed at the end of the file.

2021-08-02 14:53 UTC, deluca-mike commented on contracts/test/ERC2258.t.sol
> +    constructor() public { hevm = Hevm(address(bytes20(uint160(uint256(keccak256("hevm cheat code")))))); }
```suggestion
    constructor() public {
        hevm = Hevm(address(bytes20(uint160(uint256(keccak256("hevm cheat code"))))));
    }
```

2021-08-02 14:53 UTC, deluca-mike commented on contracts/test/ERC2258.t.sol
> +        act2    = new ERC2258Account();
```suggestion
        token = new ERC2258("Token", "TKN");
        cus1  = new Custodian();
        cus2  = new Custodian();
        act1  = new ERC2258Account();
        act2  = new ERC2258Account();
```

2021-08-02 14:53 UTC, deluca-mike commented on contracts/test/ERC2258.t.sol
> +    uint256 constant WAD = 10 ** 18;
No need for this as `WAD` is an irrelevant concept with respect to ERC2258.

2021-08-02 14:53 UTC, deluca-mike commented on contracts/test/ERC2258.t.sol
> +        assertEq(IERC20(addr).balanceOf(account), bal + amt, "Balance slot is wrong");  // Assert new balance
`mint` isn't a test and minting isn't functionality being tested, so this assertion is out of scope.

2021-08-02 14:53 UTC, deluca-mike commented on contracts/test/ERC2258.t.sol
> +pragma experimental ABIEncoderV2;
Not needed.

2021-08-02 14:53 UTC, deluca-mike commented on contracts/test/accounts/Custodian.sol
> +pragma experimental ABIEncoderV2;
Not needed.

2021-08-02 14:53 UTC, deluca-mike commented on contracts/test/accounts/ERC2258Account.sol
> +pragma experimental ABIEncoderV2;
Not needed.

2021-08-02 18:15 UTC, lucas-manuel requested changes

2021-08-02 18:15 UTC, lucas-manuel commented on config/ci.json
> +    },
Interface not needed

2021-08-02 18:15 UTC, lucas-manuel commented on config/dev.json
> +    },
Interface not needed

2021-08-02 18:15 UTC, lucas-manuel commented on config/prod.json
> +    },
Interface not needed

2021-08-02 18:15 UTC, lucas-manuel commented on contracts/test/ERC2258.t.sol
> +}
```
interface Hevm {

    function warp(uint256) external;

    function store(address,bytes32,bytes32) external;

}
```

2021-08-02 18:15 UTC, lucas-manuel commented on contracts/test/ERC2258.t.sol
> +
Extra line

2021-08-03 02:30 UTC, lucas-manuel commented on contracts/ERC2258.sol
> +        } else {
Undo this

2021-08-03 06:06 UTC, deluca-mike approved these changes

2021-08-03 13:04 UTC, lucas-manuel approved these changes

2021-08-03 13:04 UTC, merged